- name: play1
  hosts: tomcat
  become: yes
  tasks:
    - name: copying file to tomcat server
      copy:
        src: /var/lib/jenkins/workspace/jfrog_download/target/{{ version }}/jenkins-git-integration.war
        dest: /opt/apache-tomcat-10.0.27/webapps/
      notify: "Restart tomcat"

  handlers:
    - name: "Restart tomcat"
      shell: tomcatdown
      shell: tomcatup
